// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremiumDeluxeMotorSports_v1.Data;

#nullable disable

namespace PremiumDeluxeMotorSports_v1.Migrations
{
    [DbContext(typeof(PremiumDeluxeMotorSports_v1Context))]
    [Migration("20231127172400_modelschangedencorefdp")]
    partial class modelschangedencorefdp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Commande", b =>
                {
                    b.Property<int>("CmdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CmdId"), 1L, 1);

                    b.Property<int>("CustomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_Cmd")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("CmdId");

                    b.HasIndex("CustomId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Custom", b =>
                {
                    b.Property<int>("CustomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomId"), 1L, 1);

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrixCstm")
                        .HasColumnType("float");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("CustomId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Custom");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReservation"), 1L, 1);

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("int");

                    b.HasKey("IdReservation");

                    b.HasIndex("UserId");

                    b.HasIndex("VehiculeId")
                        .IsUnique();

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"), 1L, 1);

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UserBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Vehicule", b =>
                {
                    b.Property<int>("VehiculeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculeId"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("VehiculeId");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasFilter("[ReservationId] IS NOT NULL");

                    b.ToTable("Vehicule");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Commande", b =>
                {
                    b.HasOne("PremiumDeluxeMotorSports_v1.Models.Custom", "Custom")
                        .WithMany("Commandes")
                        .HasForeignKey("CustomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PremiumDeluxeMotorSports_v1.Models.User", "User")
                        .WithMany("Commandes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PremiumDeluxeMotorSports_v1.Models.Vehicule", "Vehicule")
                        .WithMany("Commandes")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Custom");

                    b.Navigation("User");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Custom", b =>
                {
                    b.HasOne("PremiumDeluxeMotorSports_v1.Models.Vehicule", "Vehicule")
                        .WithMany("Customs")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Reservation", b =>
                {
                    b.HasOne("PremiumDeluxeMotorSports_v1.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PremiumDeluxeMotorSports_v1.Models.Vehicule", "Vehicule")
                        .WithOne("Reservation")
                        .HasForeignKey("PremiumDeluxeMotorSports_v1.Models.Reservation", "VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.User", b =>
                {
                    b.HasOne("PremiumDeluxeMotorSports_v1.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Custom", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.User", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PremiumDeluxeMotorSports_v1.Models.Vehicule", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Customs");

                    b.Navigation("Reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
