// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pdm.Data;

#nullable disable

namespace pdm.Migrations
{
    [DbContext(typeof(PremiumDeluxeMotorSports_v1Context))]
    partial class PremiumDeluxeMotorSports_v1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.23");

            modelBuilder.Entity("pdm.Models.Commande", b =>
                {
                    b.Property<int>("CmdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Cmd")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CmdId");

                    b.HasIndex("CustomId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("pdm.Models.Custom", b =>
                {
                    b.Property<int>("CustomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PrixCstm")
                        .HasColumnType("REAL");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Custom");
                });

            modelBuilder.Entity("pdm.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehiculeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdReservation");

                    b.HasIndex("UserId");

                    b.HasIndex("VehiculeId")
                        .IsUnique();

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("pdm.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("pdm.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pdm.Models.Vehicule", b =>
                {
                    b.Property<int>("VehiculeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prix")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehiculeId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Vehicule");
                });

            modelBuilder.Entity("pdm.Models.Commande", b =>
                {
                    b.HasOne("pdm.Models.Custom", "Custom")
                        .WithMany("Commandes")
                        .HasForeignKey("CustomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pdm.Models.User", "User")
                        .WithMany("Commandes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pdm.Models.Vehicule", "Vehicule")
                        .WithMany("Commandes")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Custom");

                    b.Navigation("User");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("pdm.Models.Custom", b =>
                {
                    b.HasOne("pdm.Models.Vehicule", "Vehicule")
                        .WithMany("Customs")
                        .HasForeignKey("VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("pdm.Models.Reservation", b =>
                {
                    b.HasOne("pdm.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pdm.Models.Vehicule", "Vehicule")
                        .WithOne("Reservation")
                        .HasForeignKey("pdm.Models.Reservation", "VehiculeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("pdm.Models.User", b =>
                {
                    b.HasOne("pdm.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("pdm.Models.Custom", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("pdm.Models.User", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("pdm.Models.Vehicule", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Customs");

                    b.Navigation("Reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
